### ISSUE TITLE
Create architecture for SDLC

### ISSUE THREAD

**Issue by ghost** [vitech-team-sdlc/SDLC#7]
- [ ]  Architecture schema for SDLC
- [ ]  Define system modules
- [ ]  Branching strategy schema

**Comment by antonnazaruk** [comment]
is it about arch document/scheme/approach?

**Comment by ghost** [comment]
yes
